version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    restart: always

  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    restart: always

  tester:
    image: curlimages/curl:latest
    depends_on:
      - postgres
      - nodered
    entrypoint: >
      sh -c "
        echo 'Ожидание PostgreSQL...';
        until nc -z postgres 5432; do sleep 1; done;
        echo 'PostgreSQL доступен';

        echo 'Ожидание Node-RED...';
        until curl -s http://nodered:1880 > /dev/null; do sleep 1; done;
        echo 'Node-RED доступен';
      "
